dataset: CelebA # Default dataset. Options: CelebA, CUB-200, ImageNet (if implemented)
concept:
  positive: Smiling
  negative: Not_Smiling
batch_size: 32
model_name: openai/clip-vit-base-patch32
alternative_encoder_name: # e.g., facebook/dinov2-base or leave blank
surgery_alpha: 1.0
output_dir: ./outputs
save_tsne: True
run_prompt_baseline: True
run_random_edit_baseline: True
run_linear_probe_baseline: True
run_latent_probe: True
run_retrieval_eval: True
retrieval_top_k: 5
# Dataset root directories (adjust paths as necessary)
celeba_root_dir: ../data/celeba
cub_root_dir: ../data/cub
imagenet_root_dir: ../data/imagenet # Ensure this points to your ImageNet data
run_splice_baseline: False
enable_geometric_analysis: False # Placeholder for more advanced geometric analysis
enable_failure_mode_viz: False # Placeholder for visualizing failure modes
num_runs_for_stats: 5 # Set to >1 to enable statistical significance testing

# NEW: Toggle for vector trajectory plot
save_vector_trajectory: True